#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

  npx eslint --fix .
  npx prettier --write .

  echo "***Running unit tests***"
  unset ELECTRON_RUN_AS_NODE
npm run cypress -- --config video=false screenshotOnRunFailure=false